// app/(app)/colophon/page.tsx
import { LastUpdated } from "@/components/layout/last-updated";
import { AccessibleLink } from "@/components/ui/accessible-link";

/**
 * Renders the Colophon page which provides information about the website's
 * publication, development, hosting, and other technical details.
 */
export default function Colophon() {
  /**
   * The date when the website was last updated.
   */
  const updated = new Date(2025, 7, 4, 0, 19);

  return (
    <>
      <h1 className={"font-sans uppercase text-body text-4xl pb-2"}>
        Colophon
      </h1>
      <section className="flex flex-col space-y-4 [&_a]:underline text-body">
        <p>
          This website was originally published January 14th, 2024 near
          Washington, D.C. It&apos;s developed on a 2021 M1 Macbook Pro and
          hosted on{" "}
          <AccessibleLink href="https://www.digitalocean.com/">
            Digital Ocean
          </AccessibleLink>
          . All content was migrated from my previous domain emmacampbell.dev.
          The code is open source on{" "}
          <AccessibleLink href="https://github.com/emma-campbell/spooklore">
            Github
          </AccessibleLink>
          .
        </p>
        <p>
          The sans serif font for this site is{" "}
          <AccessibleLink href="https://www.fontspring.com/fonts/type-forward/garet">Garet</AccessibleLink>.
        </p>
        <p>
          This site was built using{" "}
          <AccessibleLink href="https://nextjs.org/">Next.Js</AccessibleLink>
        </p>
        <p>
          All content is hosted in Github, and uses{" "}
          <AccessibleLink href="https://keystatic.com/">Keystatic</AccessibleLink>{" "}
          to write, parse and display posts.
        </p>
        <LastUpdated date={updated} />
      </section>
    </>
  );
}

// src/routes/colophon/+page.svelte
<script lang="ts">
	import { UnderlineToBackground } from '$lib/components';
	import { DateTime } from 'luxon';

	const updated = DateTime.fromObject({ year: 2025, month: 7, day: 4 });
</script>

<svelte:head>
	<title>Colophon | Emma Campbell</title>
</svelte:head>

<h1 class="font-sans uppercase text-body text-4xl pb-2">Colophon</h1>

<section class="flex flex-col space-y-4 [&_a]:underline text-body">
	<p>
		This website was originally published January 14th, 2024 near Washington, D.C. It's developed
		on a 2021 M1 Macbook Pro and hosted on
		<a href="https://www.digitalocean.com/" target="_blank" rel="noopener noreferrer">
			<UnderlineToBackground isExternal>Digital Ocean</UnderlineToBackground>
		</a>. All content was migrated from my previous domain emmacampbell.dev. The code is open source
		on
		<a href="https://github.com/emma-campbell/spookyemma.com" target="_blank" rel="noopener noreferrer">
			<UnderlineToBackground isExternal>Github</UnderlineToBackground>
		</a>.
	</p>
	<p>
		The sans serif font for this site is
		<a href="https://www.fontspring.com/fonts/type-forward/garet" target="_blank" rel="noopener noreferrer">
			<UnderlineToBackground isExternal>Garet</UnderlineToBackground>
		</a>.
	</p>
	<p>
		This site was built using
		<a href="https://svelte.dev/" target="_blank" rel="noopener noreferrer">
			<UnderlineToBackground isExternal>SvelteKit</UnderlineToBackground>
		</a>.
	</p>
	<p>
		All content is hosted in Github as Markdown files with frontmatter, parsed using gray-matter
		and rendered with MDsveX.
	</p>
	<p class="text-sm text-muted-ink italic">
		Last updated: {updated.toLocaleString(DateTime.DATE_FULL)}
	</p>
</section>
