// app/(app)/now/page.tsx

import { Timeline, type TimelineItemProps } from "@/components/now/timeline";
import { getNowEntries } from "@/lib/keystatic";
import { compareDesc } from "date-fns";
import { MDXContent } from "@/components/mdx";

export default async function Now() {
  const nowEntries = await getNowEntries();

  // Transform the entries into timeline format
  const timelineItems: TimelineItemProps[] = await Promise.all(
    nowEntries.map(async (entry) => {
      const content = await entry.entry.content();
      return {
        month: entry.entry.month,
        year: entry.entry.year,
        children: [
          <div key={entry.slug} className="space-y-4 text-sm">
            <MDXContent content={content} />
          </div>
        ],
      };
    })
  );

  return (
    <section className="flex flex-col space-y-10 text-body">
      <div>
        <h1 className="font-sans text-4xl font-medium text-body pb-2">
          What I&apos;m doing now
        </h1>
        <p className="text-md">
          This page is updated as I do things. No particular cadence. Just when I
          feel like it.
        </p>
      </div>
      <Timeline
        items={timelineItems.sort((a, b) =>
          compareDesc(new Date(a.year, a.month), new Date(b.year, b.month))
        )}
      />
    </section>
  );
}

// src/routes/now/+page.svelte
<script lang="ts">
	import { Timeline, MdxContent } from '$lib/components';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<title>Now | Emma Campbell</title>
</svelte:head>

<section class="flex flex-col space-y-10 text-body">
	<div>
		<h1 class="font-sans text-4xl font-medium text-body pb-2">What I'm doing now</h1>
		<p class="text-md">
			This page is updated as I do things. No particular cadence. Just when I feel like it.
		</p>
	</div>

	<Timeline items={data.entries}>
		{#snippet children({ item })}
			<div class="space-y-4 text-sm">
				<MdxContent html={item.contentHtml} />
			</div>
		{/snippet}
	</Timeline>
</section>
