// app/(app)/bio/page.tsx
import Andrea from "@/public/andrea.jpeg";
import Crew from "@/public/crew.jpeg";
import Moose from "@/public/moose.jpg";
import Headshot from "@/public/headshot.jpeg";
import Image from "next/image";

export default function About() {
  return (
    <>
      <Image
        src={Headshot}
        alt={"Photo of Emma"}
        className={"h-48 w-auto rounded-lg"}
        placeholder="blur"
      />
      <section className="flex flex-col text-body pt-4 space-y-6">
        <p>
          Hey 👋 It&apos;s Emma (<i>she/any</i>). You made it to the page
          that&apos;s about me. I feel weird writing this. Seems sorta conceited
          to write about yourself. Anyways, I&apos;ll give it a whirl.
        </p>
        <p>
          I&apos;m originally from Columbus, OH, and currently live in
          Bloomington, IN with my partner and my dog. I had a quick pit-stop in
          Rochester, NY where I attended the University of Rochester to get my
          Bachelor&apos;s degree in Computer Science, and Washington, D.C. for
          a few years after college.
        </p>
        <p>
          I&apos;m a software engineer by day, and by night I&apos;m taking on
          all of the ADHD side quests my mind can hyperfixate on. I&apos;ve
          recently been learning to sew and in the past I&apos;ve built
          mechanical keyboards, refurbished Gameboys, and learned to play the
          guitar.
        </p>
        <p>
          I don&apos;t know my right from my left. No, seriously. I understand
          the concept, but if you tell me to go right I will go left. I&apos;ve
          seriously considered getting &ldquo;R&rdquo; and &ldquo;L&rdquo;
          tattooed on my hands because when I hold my hands in the shape of an
          L, they both look correct.
        </p>
        <p>
          I love the Columbus Crew, and soccer in general. It consumes my
          weekends. I got to watch the Crew win their third cup live in 2023
          and it&apos;s one of my favorite memories. I love sports in general,
          and believe that they&apos;re a great way to teach cooperation and team
          skills.
        </p>
        <p>
          I am odd and pretty introverted. I hate small talk, and prefer to
          talk about things that matter. At social gatherings, I tend to
          befriend the dog.
        </p>
        <p>
          Anyways, that&apos;s that&apos;s a pretty good overview and should
          give you a good idea about who I am as a human.
        </p>
      </section>
      <section className="grid grid-cols-3 pt-8 gap-4 [&_img]:rounded-sm">
        <Image
          priority
          src={Crew}
          placeholder="blur"
          alt="columbus crew tifo"
        />
        <Image
          priority
          src={Andrea}
          placeholder="blur"
          alt="Andrea and I on ATVs"
        />
        <Image priority src={Moose} placeholder="blur" alt="My dog Moose" />
      </section>
    </>
  );
}

// src/routes/bio/+page.svelte
<script lang="ts">
</script>

<svelte:head>
	<title>About | Emma Campbell</title>
</svelte:head>

<img src="/headshot.jpeg" alt="Emma Campbell" class="h-48 w-auto rounded-lg" />

<section class="flex flex-col text-body pt-4 space-y-6">
	<p>
		Hey 👋 It's Emma (<i>she/any</i>). You made it to the page that's about me. I feel weird
		writing this. Seems sorta conceited to write about yourself. Anyways, I'll give it a whirl.
	</p>
	<p>
		I'm originally from Columbus, OH, and currently live in Bloomington, IN with my partner and my
		dog. I had a quick pit-stop in Rochester, NY where I attended the University of Rochester to get
		my Bachelor's degree in Computer Science, and Washington, D.C. for a few years after college.
	</p>
	<p>
		I'm a software engineer by day, and by night I'm taking on all of the ADHD side quests my mind
		can hyperfixate on. I've recently been learning to sew and in the past I've built mechanical
		keyboards, refurbished Gameboys, and learned to play the guitar.
	</p>
	<p>
		I don't know my right from my left. No, seriously. I understand the concept, but if you tell me
		to go right I will go left. I've seriously considered getting "R" and "L" tattooed on my hands
		because when I hold my hands in the shape of an L, they both look correct.
	</p>
	<p>
		I love the Columbus Crew, and soccer in general. It consumes my weekends. I got to watch the
		Crew win their third cup live in 2023 and it's one of my favorite memories. I love sports in
		general, and believe that they're a great way to teach cooperation and team skills.
	</p>
	<p>
		I am odd and pretty introverted. I hate small talk, and prefer to talk about things that matter.
		At social gatherings, I tend to befriend the dog.
	</p>
	<p>
		Anyways, that's a pretty good overview and should give you a good idea about who I am as a
		human.
	</p>
</section>

<section class="grid grid-cols-3 pt-8 gap-4 [&_img]:rounded-sm">
	<img src="/crew.jpeg" alt="columbus crew tifo" />
	<img src="/andrea.jpeg" alt="Andrea and I on ATVs" />
	<img src="/moose.jpg" alt="My dog Moose" />
</section>
