// src/lib/components/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import UnderlineToBackground from './UnderlineToBackground.svelte';
	import { DateTime } from 'luxon';

	declare const __APP_VERSION__: string;
	const version = __APP_VERSION__;

	type NavItem = {
		href: string;
		text: string;
	};

	const navItems: NavItem[] = [
		{ href: '/', text: 'Notebook' },
		{ href: '/bio', text: 'About' },
		{ href: '/now', text: 'Now' }
	];

	let isMobileMenuOpen = $state(false);

	function isActive(href: string, pathname: string): boolean {
		if (href === '/') {
			return pathname === '/' || pathname.startsWith('/notebook');
		}
		return pathname === href || pathname.startsWith(href);
	}
</script>

<!-- Mobile Menu Button -->
<button
	onclick={() => (isMobileMenuOpen = !isMobileMenuOpen)}
	class="fixed top-4 left-4 z-50 p-2 lg:hidden"
	aria-label="Toggle menu"
>
	<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
		{#if isMobileMenuOpen}
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M6 18L18 6M6 6l12 12"
			/>
		{:else}
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M4 6h16M4 12h16M4 18h16"
			/>
		{/if}
	</svg>
</button>

<!-- Overlay for mobile -->
{#if isMobileMenuOpen}
	<button
		class="fixed inset-0 bg-black/50 z-40 lg:hidden"
		onclick={() => (isMobileMenuOpen = false)}
		aria-label="Close menu"
	></button>
{/if}

<!-- Sidebar -->
<aside
	class="
		fixed inset-y-0 left-0 w-48 bg-background px-6 py-12 overflow-y-auto z-40
		transform transition-transform duration-300 ease-in-out
		{isMobileMenuOpen ? 'translate-x-0' : '-translate-x-full'}
		lg:translate-x-0
	"
>
	<div class="flex flex-col h-full">
		<!-- Name -->
		<div class="mb-12">
			<h1 class="text-lg font-bold">Emma Campbell</h1>
			<p class="text-sm text-muted-ink italic">A collection of notes and thoughts</p>
		</div>

		<!-- Navigation -->
		<nav class="flex-grow">
			<ul class="space-y-1">
				{#each navItems as item}
					{@const active = isActive(item.href, $page.url.pathname)}
					<li>
						<a
							href={item.href}
							onclick={() => (isMobileMenuOpen = false)}
							class="block py-1 text-sm"
						>
							<UnderlineToBackground isActive={active}>
								{item.text}
							</UnderlineToBackground>
						</a>
					</li>
				{/each}
			</ul>
		</nav>

		<!-- Footer Links -->
		<div class="space-y-1 text-sm">
			<a
				href="https://github.com/spookyemma"
				target="_blank"
				rel="noopener noreferrer"
				class="block py-1"
			>
				<UnderlineToBackground isExternal>GitHub</UnderlineToBackground>
			</a>
			<a href="/rss.xml" class="block py-1"> RSS </a>
		</div>

		<!-- Copyright -->
		<div class="mt-8 pt-4 border-t border-muted-ink/20">
			<p class="text-xs text-muted-ink">© 2022–{DateTime.now().year} Emma Campbell</p>
			<a href="/changelog" class="text-xs text-muted-ink hover:text-accent transition-colors">
				v{version}
			</a>
		</div>
	</div>
</aside>

// components/layout/sidebar/index.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { UnderlineToBackground } from "@/components/ui/underline-to-background";
import { DateTime } from "luxon";

type NavItem = {
  href: string;
  text: string;
};

const navItems: NavItem[] = [
  { href: "/", text: "Notebook" },
  { href: "/chronicling", text: "Chronicling" },
];

export const Sidebar = () => {
  const pathname = usePathname() || "/";
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  return (
    <>
      {/* Mobile Menu Button */}
      <button
        onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
        className="fixed top-4 left-4 z-50 p-2 lg:hidden"
        aria-label="Toggle menu"
      >
        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          {isMobileMenuOpen ? (
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          ) : (
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
          )}
        </svg>
      </button>

      {/* Overlay for mobile */}
      {isMobileMenuOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-40 lg:hidden"
          onClick={() => setIsMobileMenuOpen(false)}
        />
      )}

      {/* Sidebar */}
      <aside className={`
        fixed inset-y-0 left-0 w-48 bg-background px-6 py-12 overflow-y-auto z-40
        transform transition-transform duration-300 ease-in-out
        ${isMobileMenuOpen ? 'translate-x-0' : '-translate-x-full'}
        lg:translate-x-0
      `}>
      <div className="flex flex-col h-full">
        {/* Name */}
        <div className="mb-12">
          <h1 className="text-lg font-bold">Emma Campbell</h1>
          <p className="text-sm text-muted-ink italic">A collection of notes and thoughts</p>
        </div>

        {/* Navigation */}
        <nav className="flex-grow">
          <ul className="space-y-1">
            {navItems.map((item) => {
              const isActive = pathname === item.href ||
                (item.href !== "/" && pathname.startsWith(item.href));

              return (
                <li key={item.href}>
                  <Link
                    href={item.href}
                    onClick={() => setIsMobileMenuOpen(false)}
                    className="block py-1 text-sm"
                  >
                    <UnderlineToBackground isActive={isActive}>
                      {item.text}
                    </UnderlineToBackground>
                  </Link>
                </li>
              );
            })}
          </ul>
        </nav>

        {/* Footer Links */}
        <div className="space-y-1 text-sm">
          <a
            href="https://github.com/spookyemma"
            target="_blank"
            rel="noopener noreferrer"
            className="block py-1"
          >
            <UnderlineToBackground isExternal>
              GitHub
            </UnderlineToBackground>
          </a>
          <a
            href="https://twitter.com/spookyemma"
            target="_blank"
            rel="noopener noreferrer"
            className="block py-1"
          >
            <UnderlineToBackground isExternal>
              Twitter
            </UnderlineToBackground>
          </a>
          <a
            href="/rss.xml"
            className="block py-1"
          >
            <UnderlineToBackground>
              RSS
            </UnderlineToBackground>
          </a>
        </div>

        {/* Copyright */}
        <div className="mt-8 pt-4 border-t border-muted-ink/20">
          <p className="text-xs text-muted-ink">
            © 2022–{DateTime.now().year} Emma Campbell
          </p>
        </div>
      </div>
    </aside>
    </>
  );
};
